### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by ZAYEC77** [rmrevin/yii2-comments#10]
Hello, nice module.
I want to create nested comments.
Is it possible with your package?

**Comment by rmrevin** [comment]
Good day. I'm glad you like my extension. Unfortunately, in this version you cannot make a tree of comments. You can modify the extension and send pull request. Or to look at market extensions. There is one version with the nested comments. But I'm not sure of the quality of implementation.
https://github.com/DigitalGoldfish/yii2-comments

**Comment by ZAYEC77** [comment]
Thanks
