### ISSUE TITLE
canUpdate и canDelete всегда возвращают false

### ISSUE THREAD

**Issue by PostelWagner** [rmrevin/yii2-comments#11]
Привет, использую Rbac 
но методы [canUpdate](https://github.com/rmrevin/yii2-comments/blob/master/models/Comment.php#L106) и [canDelete](https://github.com/rmrevin/yii2-comments/blob/master/models/Comment.php#L118) всегда возвращают false

все начинает работать нормально, если выражение 
$User->isGuest ? false : $this->created_by === $User->id
заключить в скобки

**Comment by rmrevin** [comment]
@PostelWagner Так если используется rbac до этого места интерпритатор вообще не должен дойти. Если используется rbac, то будет использована проверка - `\Yii::$app->getUser()->can(Comments\Permission::UPDATE)` 

Тем не менее добавил скобки в версии 1.4.1

**Comment by PostelWagner** [comment]
ОК, спасибо за оперативный ответ

Для примера вот:
`true ? true : false ? false : false` - возвращает false
`true ? true : (false ? false : false)` - возвращает true

PHP 5.6.17
