### ISSUE TITLE
rmrevin yii2-comments Unknown author

### ISSUE THREAD

**Issue by nelli7** [rmrevin/yii2-comments#4]
Hello! 
 When I add a comment it works fine, but it writes Unknown author.
In data base "created_by" is filled correctly, 1, 2 etc.

Could you please explain how can I display username instead of Unknown author?

**Comment by rmrevin** [comment]
You should assign your model user interface ["CommentatorInterface"](https://github.com/rmrevin/yii2-comments/blob/master/interfaces%2FCommentatorInterface.php)

**Comment by nelli7** [comment]
If I assign my model in  "CommentatorInterface" , if I run composer install it will be broken? Or should  I overwrite these methods in my own model "User" ? Thank you for the answer!

**Comment by nelli7** [comment]
Okay, now I can get only one username for all comments. This method "public function getCommentatorName();" returns  string, but there are many users that can comment,could you please tell me how can I get them all, if it returns string?)

**Comment by rmrevin** [comment]
@nelli7 You have anonymous comments?
I'm afraid if this expansion will not help you.
You will have to extend the functionality of their own.

**Comment by nelli7** [comment]
I have view for Task. Registered users can leave comments in view of Tasks. And I am trying to get their usernames, in table comments we have created_by. created_by contains users id. And I thought that I can get their usernames somehow, but I can return only one user)
