### ISSUE TITLE
composer update failed

### ISSUE THREAD

**Issue by mathedu4all** [rmrevin/yii2-comments#9]
> composer require "rmrevin/yii2-comments:*"

  [RuntimeException]  
  Could not load package rmrevin/yii2-fontawesome in http://packagist.org: [U  
  nexpectedValueException] Could not parse version constraint v4.1._: Invalid  
   version string "v4.1._"  

  [UnexpectedValueException]  
  Could not parse version constraint v4.1._: Invalid version string "v4.1._"

**Comment by rmrevin** [comment]
Hello.
Update composer, clean cache and update packages in project.

**Comment by osCMattiFinn** [comment]
We cannot update packages because it throws this error every time we try.

**Comment by arswarog** [comment]
Hello.
php composer.phar global require "fxp/composer-asset-plugin:~1.1.1"
Update composer, clean cache and update packages in project.

**Comment by rmrevin** [comment]
@arswarog Thanks for answer.
@osCMattiFinn You have to update the plugin `fxp/composer-asset-plugin` to last version

```
php composer.phar global require "fxp/composer-asset-plugin:~1.1.1"
php composer.phar self-update
php composer.phar clear-cache
php composer.phar update
```

**Comment by osCMattiFinn** [comment]
I ran the above commands rmrevin and receive the following error while running composer update:

The requested package mrevin/yii2-fontawesome could not be found in any version, there may be a typo in the package name.

I get the same error if I try to install any package.

**Comment by rmrevin** [comment]
@osCMattiFinn Check the package name. The package is named `rmrevin/yii2-fontawesome`

**Comment by osCMattiFinn** [comment]
You are right.  I think that some other developer who has used your package along with their own has made an error.

**Comment by rmrevin** [comment]
@osCMattiFinn do not quite understand. With the extension everything seems to be fine?

**Comment by osCMattiFinn** [comment]
It looks to be good now, update appears to be running normally and I saw that your package got installed.

I simply adjusted the composer.json file to correct the typo.  This is not a file I have previously manually edited, so the error must have come from a package I installed (and probably not used).

**Comment by ankhanguit** [comment]
does it work in yii2 advanced?

**Comment by rmrevin** [comment]
@arswarog yes.

**Comment by apps25** [comment]
Hi 
I am facing the same issue but i am unable to fix it. I tried all but all in vain.
